#!/usr/bin/env bash
# Parallel build of all federate__* CCpp federates under fed-gen/.
# Expects scaffold already generated by `lfc-dev --no-compile lf-src/AutowareFederated.lf`.
#
# Usage:
#   bash lf-src/parallel_build.sh                   # resume: skip already-ok federates
#   bash lf-src/parallel_build.sh --clean           # force full rebuild
#   P=8 J=2 bash lf-src/parallel_build.sh           # override parallelism

set -u

CLEAN=0
while [ $# -gt 0 ]; do
    case "$1" in
        --clean) CLEAN=1; shift ;;
        -h|--help)
            sed -n '2,8p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "unknown flag: $1" >&2; exit 2 ;;
    esac
done

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

# Env: ROS + Autoware install + LF_AUTOWARE_HOME, conda stripped.
set +u
source /opt/ros/humble/setup.bash
source install/setup.bash 2>/dev/null
set -u
export LF_AUTOWARE_HOME="$REPO"
unset CONDA_EXE CONDA_PREFIX CONDA_PROMPT_MODIFIER CONDA_SHLVL CONDA_PYTHON_EXE CONDA_DEFAULT_ENV _CE_CONDA
export PATH=$(echo $PATH | tr ':' '\n' | grep -v conda | tr '\n' ':' | sed 's/:$//')
export LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | tr ':' '\n' | grep -v conda | tr '\n' ':' | sed 's/:$//')

FED_ROOT="$REPO/fed-gen/AutowareFederated"
LOG_DIR="$REPO/logs/parallel_build"
mkdir -p "$LOG_DIR"

# Tunables
P="${P:-10}"   # concurrent federates
J="${J:-2}"   # threads per federate (total peak load ~= P * J)

# --clean: wipe markers and logs for a full rebuild.
# Default (resume): keep .ok markers so already-built federates are skipped;
# retry .fail ones (wipe their markers + stale logs).
if [ "$CLEAN" = "1" ]; then
    rm -f "$LOG_DIR"/*.ok "$LOG_DIR"/*.fail "$LOG_DIR"/*.log
else
    rm -f "$LOG_DIR"/*.fail
    # drop logs for federates that need to run this pass
    for log in "$LOG_DIR"/*.log; do
        [ -f "$log" ] || continue
        name=$(basename "$log" .log)
        [ -f "$LOG_DIR/${name}.ok" ] || rm -f "$log"
    done
fi

build_one() {
    local fed_dir="$1"
    local fed_name
    fed_name="$(basename "$fed_dir")"
    # short tag = federate short name (e.g. "sd" from "federate__sd"), padded for alignment
    local tag="${fed_name#federate__}"
    local log="$LOG_DIR/${fed_name}.log"

    # Resume: if .ok marker exists, skip this federate entirely.
    if [ -f "$LOG_DIR/${fed_name}.ok" ]; then
        printf '>>>> [%(%H:%M:%S)T] SKIP %s (already ok) <<<<\n' -1 "$fed_name"
        return 0
    fi

    local start_ts end_ts rc elapsed
    start_ts=$(date +%s)

    # Stream all build output to both stdout (prefixed with federate tag) and log file.
    # Each line gets "[tag    ] " prefix so interleaved output is readable.
    {
        echo "=== $fed_name start $(date +%H:%M:%S) ==="
        cmake -S "$fed_dir" -B "$fed_dir/build" \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX="$FED_ROOT" \
              -DCMAKE_INSTALL_BINDIR=bin \
        && cmake --build "$fed_dir/build" --target install --parallel "$J"
        rc=$?
        end_ts=$(date +%s)
        elapsed=$(( end_ts - start_ts ))
        echo "=== $fed_name end $(date +%H:%M:%S) rc=$rc elapsed=${elapsed}s ==="
        exit $rc
    } 2>&1 \
      | awk -v t="$tag" 'BEGIN{printf ""} {printf "[%-8s] %s\n", t, $0; fflush()}' \
      | tee "$log"

    rc=${PIPESTATUS[0]}
    end_ts=$(date +%s)
    elapsed=$(( end_ts - start_ts ))
    if [ "$rc" = 0 ]; then
        touch "$LOG_DIR/${fed_name}.ok"
        printf '>>>> [%(%H:%M:%S)T] OK   %s (%ds) <<<<\n' -1 "$fed_name" "$elapsed"
    else
        touch "$LOG_DIR/${fed_name}.fail"
        printf '>>>> [%(%H:%M:%S)T] FAIL %s (%ds) — see %s <<<<\n' -1 "$fed_name" "$elapsed" "$log"
    fi

    # Progress counter
    local ok_n fail_n total
    ok_n=$(ls "$LOG_DIR"/*.ok 2>/dev/null | wc -l)
    fail_n=$(ls "$LOG_DIR"/*.fail 2>/dev/null | wc -l)
    total=$(find "$FED_ROOT/src-gen" -maxdepth 1 -mindepth 1 -type d -name 'federate__*' | wc -l)
    printf '>>>> progress: %d ok, %d failed, out of %d <<<<\n' "$ok_n" "$fail_n" "$total"
}
export -f build_one
export FED_ROOT LOG_DIR J

TOTAL=$(find "$FED_ROOT/src-gen" -maxdepth 1 -mindepth 1 -type d -name 'federate__*' | wc -l)
echo "=== Building $TOTAL federates with -P$P -j$J ==="
START_TS=$(date +%s)

find "$FED_ROOT/src-gen" -maxdepth 1 -mindepth 1 -type d -name 'federate__*' \
  | xargs -n1 -P"$P" -I{} bash -c 'build_one "$@"' _ {}

END_TS=$(date +%s)
OK_COUNT=$(ls "$LOG_DIR"/*.ok 2>/dev/null | wc -l)
FAIL_COUNT=$(ls "$LOG_DIR"/*.fail 2>/dev/null | wc -l)
echo ""
echo "=== BUILD SUMMARY: $OK_COUNT ok, $FAIL_COUNT failed (elapsed $((END_TS-START_TS))s) ==="
if [ "$FAIL_COUNT" -gt 0 ]; then
    echo "Failed federates:"
    ls "$LOG_DIR"/*.fail | sed 's|.*/||; s|\.fail$||'
    exit 1
fi
echo "ALL OK"
